---
name: Lint and Test Charts

on: pull_request

jobs:
  lint-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        kubernetes_version:
          # See https://kubernetes.io/releases/ for EOL dates
          - "kindest/node:v1.27.2"
          - "kindest/node:v1.26.4"
          - "kindest/node:v1.25.9"
          - "kindest/node:v1.24.13"
      fail-fast: false

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11.4

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2
        with:
          version: v3.8.0

      - name: Run chart-testing (list-changed)
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml)
          if [ -n "${changed}" ]; then
            echo "changed=true" >> "${GITHUB_OUTPUT}"
          fi

      - name: install helm unittests
        if: steps.list-changed.outputs.changed == 'true'
        run: |
          helm env
          helm plugin install https://github.com/quintush/helm-unittest --version 0.2.11

      - name: Run chart-testing (lint)
        run: ct lint --config ct.yaml

      - name: Create kind cluster
        uses: helm/kind-action@v1.8.0
        if: steps.list-changed.outputs.changed == 'true'
        with:
          node_image: ${{ matrix.kubernetes_version }}

      - name: Run chart-testing (install)
        run: ct install --config ct.yaml
